/* Assignment2
       Theory questions

   1) What is npm ?
   A: Npm is a website which provides various packages to install and manage them in your product. NPM abbreviation is 
      not Node package manager, but it sorts of does manage packages 
      
   2) What is parcel/webpack ? Why do we need it ?
   A: Parcel webpack is a dev dependency package which acts as bundler ( optimisations , tree shaking , etc.) and it goes to index.html , builds a '
      dev build and hosts it on the server.

   3) What is .parcel-cache?
   A: Parcel cache kind of stores the build files , which can be retrieved and used whenever we run npx parcel index.html.
      It kind of reduces time when building

   4) What is npx ?
   A: npx executes the packages , whereas npm installs the packages

   5) What is the difference between dev dependencies and dependencies?
   A: Whenevr we are developing the code , we do need some dependencies which can make our coding/debugging easier 
      Whenever we are installing the product in a environment, we need some production dependencies to optimise or do any 
      operations specific to production

      Eg : dev dependency : Babel/ESLint
           dependency : React

  6) What is tree shaking ?
  A: Tree shaking is a technique often used in web development and in javascript. It helps us to eliminate dead code/unused code
     Bundler does static analysis of code and analyses used and unused modules and then eliminates the code and bundles 
     Parcel does it for us

  7) What is Hot Module replacement?
  A: Hot Module replacement is a feature in modern web development tools which loads aome part of the page without actually re
    freshing the page. The  changes in code base are replicated immediately in the browser

  8) List down 5 favourite super powers of parcel and describe any 3 of them in your own words?
  A: Parcel has many super powers . Some of them are
     1) Provides dev build
     2) Hosts on local Server
     3) Hot Module replacement
     4)Uses a File watching algorithm which is written in c++
     5) Caching
     6)Image optimisation
     7) Minification
     8) Tree Shaking
     9) Consistent hashing
     etc.. refer parcel documentation

 9) What is .gitignore ? What should we add and what should not be added to it?
 A:  Git ignore is a file in github repository telling git to ignore some modules / folders/ files
     The files / folders which can be regenrated should  be added to  git ignore

     Eg: package.json and package-lock.json are enough to generate node modules , hence node modules are added in git ignore

 10)What is the difference between package.json and package-lock.json
 A:  package.json
     a) It contains package meta data for a node js project and shared with project
     b) It can be manually edited and contains the versioning of packages

     package-lock.json
     a) It contains exactly the installed version of package and also have information about dependency packages
     b) It cannot be edited manually and often generated by npm when packages are installed

11) Why should I not modify package-lock.json?
A: Editing package-lock.json can potentially introduce security vulnerabilities, and package version change can impact other
   developers too.

12) What is node_modules and is it good idea to push them to git?
A: Node modules are generated when we install mentioned packages in package.json , these contain all the tree dependency packages
   and No we should not push tem to git , as they can be regenerated

13) What is the dist folder?
A: In a React app, the dist folder typically stands for "distribution" and is commonly used to store the final,
 optimized, and production-ready version of the application. 

 14)What is brwoserlists. Read about diff bundlers : vite, webpack and parcel
 A: Browser lists are mentioned in front-end applications generally to target list of browsers


*/